# Generated by Django 5.2.17 on 2026-08-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EssayAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_text",
                    models.TextField(
                        blank=True,
                        help_text="Исходный текст для сочинения (опционально)",
                    ),
                ),
                ("essay_text", models.TextField(blank=True)),
                (
                    "checklist",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Словарь {код критерия: bool} — самопроверка по чек-листу",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("rus", "Русский язык"),
                            ("math_base", "Математика (база)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("short_answer", "Краткий ответ"),
                            ("choice", "Выбор варианта"),
                            ("essay", "Сочинение"),
                        ],
                        default="short_answer",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Список вариантов ответа для заданий с выбором (JSON-массив строк)",
                        null=True,
                    ),
                ),
                ("correct_answer", models.CharField(max_length=500)),
                ("explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("base", "Базовый"),
                            ("advanced", "Повышенный"),
                            ("high", "Высокий"),
                        ],
                        default="base",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="seed", max_length=20)),
                (
                    "fipi_id",
                    models.CharField(
                        blank=True,
                        help_text="Идентификатор задания в открытом банке ФИПИ",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["topic_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_limit_minutes", models.PositiveIntegerField(default=180)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "Идёт"), ("finished", "Завершён")],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_variants",
                        to="exam.subject",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="exam_variants", to="exam.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(blank=True, max_length=1000)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("practice", "Тренировка"),
                            ("exam", "Вариант на время"),
                        ],
                        default="practice",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exam.examvariant",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exam.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_number",
                    models.PositiveSmallIntegerField(
                        help_text="Номер задания в КИМ ЕГЭ"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="exam.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject_id", "task_number"],
                "unique_together": {("subject", "task_number")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="exam.topic",
            ),
        ),
    ]
