# Generated by Django 5.2.17 on 2026-08-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="essayattempt",
            name="essay_type",
            field=models.CharField(
                choices=[
                    ("ege", "Сочинение ЕГЭ (задание 27)"),
                    ("final", "Итоговое сочинение"),
                ],
                default="ege",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="essayattempt",
            name="source_text",
            field=models.TextField(
                blank=True,
                help_text="Исходный текст для сочинения ЕГЭ или тема — для итогового сочинения (опционально)",
            ),
        ),
    ]
